name: migex
channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - snakemake-minimal
  - pyyaml
  - apptainer
  - bakta
  - r-base
  - r-rmarkdown
  - r-ggplot2
  - r-stringr
  - r-ggpubr
  - r-dplyr
  - r-cowplot
  - r-png
  - r-jsonlite
  - tectonic

  - r-kableextra